# Generated by Django 3.2 on 2021-11-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(max_length=50, verbose_name='Company Name')),
                ('RefNo', models.CharField(max_length=50, verbose_name='Company Registration Number')),
                ('FinancialYearEnd', models.DateField()),
                ('ProvisionalTaxDate1', models.DateField()),
                ('ProvisionalTaxDate2', models.DateField()),
                ('ARMonth', models.DateField()),
                ('TaxRegNo', models.CharField(max_length=50, verbose_name='Tax Registration Number')),
                ('StreetName', models.CharField(max_length=50, verbose_name='Street Name')),
                ('StreetNo', models.CharField(max_length=50, verbose_name='Street Number (if applicable)')),
                ('BuildingName', models.CharField(max_length=50, verbose_name='Building Name (if applicable)')),
                ('BuildingNo', models.CharField(max_length=50, verbose_name='Building Number (if applicable)')),
                ('Suburb', models.CharField(max_length=50, verbose_name='Suburb')),
                ('City', models.CharField(max_length=50, verbose_name='City')),
                ('ContactPerson', models.CharField(max_length=50, verbose_name='Contact Person')),
                ('OfficeNumber', models.CharField(max_length=50, verbose_name='OfficeNumber')),
                ('CellNumber', models.CharField(max_length=50, verbose_name='Cell Number')),
                ('EmailAddress', models.CharField(max_length=50, verbose_name='E-mailAddress')),
                ('IT14', models.BooleanField(default=True)),
                ('FinancialStatements', models.BooleanField(default=True)),
                ('IsProvisionalTaxPayer', models.BooleanField(default=True)),
                ('AnnualReturns', models.BooleanField(default=True)),
                ('isdone_IT12', models.BooleanField(default=False)),
                ('isdone_FinancialStatements', models.BooleanField(default=False)),
                ('isdone_Provisionals', models.BooleanField(default=False)),
                ('isdone_AnnualReturns', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='IndividualClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Surname', models.CharField(max_length=50, verbose_name='Company Name')),
                ('Name', models.CharField(max_length=50, verbose_name='Company Name')),
                ('IDNo', models.CharField(max_length=11, verbose_name='Company Name')),
                ('ProvisionalTaxDate1', models.DateField()),
                ('ProvisionalTaxDate2', models.DateField()),
                ('TaxRegNo', models.CharField(max_length=50, verbose_name='Tax Registration Number')),
                ('StreetName', models.CharField(max_length=50, verbose_name='Street Name')),
                ('StreetNo', models.CharField(max_length=50, verbose_name='Street Number (if applicable)')),
                ('BuildingName', models.CharField(max_length=50, verbose_name='Building Name (if applicable)')),
                ('BuildingNo', models.CharField(max_length=50, verbose_name='Building Number (if applicable)')),
                ('Suburb', models.CharField(max_length=50, verbose_name='Suburb')),
                ('City', models.CharField(max_length=50, verbose_name='City')),
                ('ContactPerson', models.CharField(max_length=50, verbose_name='Contact Person')),
                ('CellNumber', models.CharField(max_length=50, verbose_name='Cell Number')),
                ('EmailAddress', models.CharField(max_length=50, verbose_name='E-mailAddress')),
                ('IT12', models.BooleanField(default=True)),
                ('IsProvisionalTaxPayer', models.BooleanField(default=True)),
                ('isdone_IT12', models.BooleanField(default=False)),
                ('isdone_Provisionals', models.BooleanField(default=False)),
            ],
        ),
    ]
