# Generated by Django 3.2 on 2022-02-01 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220120_2203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyclass',
            old_name='isdone_IT12',
            new_name='isdone_IT14',
        ),
    ]
